# -*- coding: utf-8 -*-
"""
批次簡報示意圖生成腳本

使用 C:\\Users\\vm\\.agents\\skills\\draw\\draw.py (gpt-image-2 模型)
逐頁為 15 張投影片生成精美的 3D 科技極簡示意圖，並自動命名為 slide_1.png 到 slide_15.png。
"""

import os
import subprocess
import glob
import shutil
from pathlib import Path

# 視覺風格定義
STYLE_TOKENS = "minimalist 3D render, clean tech style, futuristic educational concept, glowing neon cyan and dark blue lights, soft shadows, studio lighting, high resolution, professional slide illustration, isometric viewport"

# 15 張投影片的生圖 Prompt 字典
SLIDE_PROMPTS = {
    1: "future classroom with floating glowing lines and hologram control panels",
    2: "one teacher working late in front of a computer screen, with messy code windows, subtitle timelines, and slide drafts in background, dim light ambient",
    3: "chat bubble icon on left, intricate golden gears and terminal console on right, symbolizing transition from talk to action",
    4: "abstract anti-gravity wave background with gradient of dark blue and teal, tiny glowing particles, high tech texture",
    5: "VS Code editor interface with install button of Antigravity plugin and simple icon of project folder initialization",
    6: "exquisite system settings menu icon, with strong emphasis on a glowing green security shield and padlock, representing permissions control",
    7: "exquisite chat bubble containing @ symbol, paperclip for media, and Chrome browser icon, neon light style",
    8: "a glowing futuristic spellbook with YAML code snippets and commands floating out of the pages, tech light style",
    9: "a film strip with glowing audio waveforms and auto-generated Chinese subtitle tracks floating on it, a pair of scissors cutting highlights nearby",
    10: "wireframe slides, with code generation flow and beautiful illustrations generated by AI, symbolizing slide automation",
    11: "a glowing cloud icon connected to GitHub logo and Firebase logo, glowing data streams shooting towards a hand holding a phone",
    12: "glowing sci-fi brain hemisphere on left, exquisite glowing robotic arm on right, connected with energy lines",
    13: "a markdown document automatically syncing and transferring from notepad interface to editor terminal interface with dynamic glowing lines",
    14: "a teacher standing on a glowing staircase, guiding students to look towards a bright and glorious future learning landscape",
    15: "a glowing circular sci-fi portal tunnel, symbolizing the journey towards a new starting point of technology and education"
}

def main():
    script_path = r"C:\Users\vm\.agents\skills\draw\draw.py"
    target_dir = Path(r"g:\我的雲端硬碟\antigravity2\antigravity learning\slides\images")
    temp_out_dir = Path(r"g:\我的雲端硬碟\antigravity2\antigravity learning\slides\temp_gen")
    
    # 建立目錄
    target_dir.mkdir(parents=True, exist_ok=True)
    
    print("=== GPT-image-2 簡報示意圖批次生成系統 ===")
    print(f"風格政策: {STYLE_TOKENS}\n")

    for page_num, brief in SLIDE_PROMPTS.items():
        # 清空暫存目錄以確保能找到最新生成的檔案
        if temp_out_dir.exists():
            shutil.rmtree(temp_out_dir)
        temp_out_dir.mkdir(parents=True, exist_ok=True)
        
        full_prompt = f"{STYLE_TOKENS}, {brief}"
        name_prefix = f"slide_{page_num}_raw"
        
        print(f"\n[頁面 {page_num}/15] 正在生圖...")
        print(f"  提示詞: {brief}")
        
        # 呼叫 draw.py 進行生圖
        cmd = [
            "python", script_path,
            full_prompt,
            "--name", name_prefix,
            "--outdir", str(temp_out_dir),
            "--quality", "low"  # 確保費用低且速度快
        ]
        
        try:
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            print("  [生圖成功]")
            
            # 尋找產生的檔案並重命名移動至目標資料夾
            gen_files = glob.glob(str(temp_out_dir / f"{name_prefix}_*.png"))
            if gen_files:
                new_filename = f"slide_{page_num}.png"
                dest_path = target_dir / new_filename
                shutil.move(gen_files[0], dest_path)
                print(f"  [部署成功] 已移動至: {dest_path}")
            else:
                print(f"  [警告] 找不到產生的圖檔！")
        except subprocess.CalledProcessError as e:
            print(f"  [錯誤] 執行 draw.py 失敗！")
            print(f"  錯誤訊息: {e.stderr}")
            
    # 清理暫存資料夾
    if temp_out_dir.exists():
        shutil.rmtree(temp_out_dir)
    print("\n=== 所有投影片示意圖生成並部署完成！ ===")

if __name__ == "__main__":
    main()
